### PR TITLE
Implemented NIP28

### PR DESCRIPTION
**Pull request by guilhermegps**
It was created implementation of NIP28 and changed some structures.

Also was Fixed some bugs and improved some code.

### CODE REVIEW

**Comment by guilhermegps** [comment]
Please, wait a little.

I detected some bugs, I will solve it.

**Comment by guilhermegps** [comment]
Now it looks good. Go ahead.

**Comment by tcheeric** [comment]
Ok, cool. I am working on it. Thanks.

**Comment by tcheeric** [comment]
I had forgotten to push some changes I made. It's about segregating Identities from Profiles. I am keeping the identity simple without Profile, with only public and private keys.  
Could you please integrate that in your code and submit another PR?
Thanks!

**Comment by guilhermegps** [comment]
Ok, no problem.

**Comment by guilhermegps** [comment]
Done

**Comment by tcheeric** [comment]
Thanks. Will work on this tomorrow.

**Comment by tcheeric** [comment]
Hi @guilhermegps , I see that you are using the json jackson library and it makes me very much regret not using it from the start. In the long run, it's probably a good idea to fully transition to it? I think it will make the code much cleaner, and also, I think it could be confusing to maintain both. 
What do you think?

**Comment by guilhermegps** [comment]
Actually I'm already working at it haha. I'll open an issue for it.

**Pull request merged**
