### PR TITLE
Removing type's marshallers

### PR DESCRIPTION
**Pull request by guilhermegps**
I can't find a reason for this marshallers. All looks working fine without they.

Could you check if is better with this change? Please

### CODE REVIEW

**Comment by tcheeric** [comment]
I am not sure, I'll need to check, but I think they're used by the GenericTag,  GenericEvent, GenericMessage, ExpressionValue classes for generating custom Events, Tags, Messages etc, that are not supported out of the box by the library.

**Comment by guilhermegps** [comment]
Any position?

**Comment by tcheeric** [comment]
I've been experimenting with some new stuff lately but I'll definitely look into this again tonight. I believe it's needed but I could be wrong...

--
Sent with Tutanota, enjoy secure & ad-free emails.



24 Apr 2023, 17:58 by ***@***.***:

**Comment by guilhermegps** [comment]
Did you test this branch? What had happened when you test all features on this branch? You found some error? 

If you don't have any problem, we may to merge it.

**Comment by tcheeric** [comment]
I have not yet, actually. I put it on the back burner to focus on the release. I'll look now into it
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



24 Apr 2023, 18:15 by ***@***.***:

**Comment by tcheeric** [comment]
I think you need the type marshallers, else you run into a situation like this one in the EventUnmarshaller class where the value is not properly decoded, this is because of the missing type-marshallers. 

image
 
I noticed the issue while running nostr.test.event.EventTest.testUnmarshallEvent()

I am debugging to see how to fix this for now.

Eventually, we will have to get rid of them as well, but we need to proceed carefully.

**Comment by tcheeric** [comment]
I'll hopefully find a solution for this later today. I'll let you know...

**Comment by guilhermegps** [comment]
Well... I can't see sense in have "type marshallers" for "type unmarshallers" to work correctly.

This has me thinking, maybe we're not seeing the full extent of the problem.

Why we need these types? 

Why we need an POJO named "ObjectValue" intead of just use java native "Object"?


Why use any type of these?

image


I think we need to migrate to Jackson Unmarshall and just use Java native types.


What do you think about it?

**Comment by tcheeric** [comment]
I fully agree! This just adds unnecessary bloat and needs to be removed. I'll focus on that from now on. 
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



25 Apr 2023, 18:57 by ***@***.***:

**Comment by tcheeric** [comment]
I wrote this a while ago, so I needed to review again, so here is what I have found:

- The unmarshaller classes are completely irrelevant to the protocol and can be removed.
- Same for the parser classes, they are now obsolete
- That means we can get rid of nostr-types and nostr-json modules.
- There are a few other places that will also need to get modified to use jackson:
1. InternetIdentifierMetadataEvent.setContent()
2. Nip05Validator.getPublicKey()
3. Connection.updateRelayMetadata()
- nostr.event.impl.OtsEvent will need to get rewritten, because of its dependency to ExpressionValue. Same for ElementAttribute, to remove the dependence to IValue.

Thoughts?

**Comment by guilhermegps** [comment]
I think we can open a specific issue for these analyses. Can you open it?

**Comment by tcheeric** [comment]
We have one already, I think. Let's use this one? 

https://github.com/tcheeric/nostr-java/issues/15

**Comment by tcheeric** [comment]
@guilhermegps, I have now created issues #29 and #30.

**Pull request closed without merging**
